### ISSUE TITLE
Oraclize version and exchange API endpoint require updating

### ISSUE THREAD

**Issue by Klmattis** [fravoll/solidity-patterns#10]
Within solidity-patterns/Oracle/oracle.sol:

The oraclize import should be changed to "github.com/oraclize/ethereum-api/oraclizeAPI_0.4.sol" to maintain compatibility (the other option being updating the compiler version to 0.5.0).

Also, the api.fixer.io endpoint is now deprecated, and the new endpoint requires an API key to use. To fix this, the "https://api.exchangeratesapi.io/latest?symbols=USD" endpoint can be used as a drop-in replacement to the fixer endpoint.

Thanks!

**Comment by fravoll** [comment]
Thanks for your input. I incoorporated the proposed changes.
