### ISSUE TITLE
Add License for both documentations and source codes.

### ISSUE THREAD

**Issue by aisuzuki** [fravoll/solidity-patterns#11]
It would be helpful if there's explicit license name on each objects in this repository. 
(e.g, MIT, GPLv3, etc)

We are planning to make Smart Contract Design Pattern repository with code executable environment, and wondering if we could include your patterns or not.

**Comment by fravoll** [comment]
There is an MIT license in the root which is applicable for the whole repository. So feel free to include the patterns into your repository :)
But please be aware that they might not  be up-to-date for the current Solidity version.
