### ISSUE TITLE
Diamond Pattern

### ISSUE THREAD

**Issue by mudgen** [fravoll/solidity-patterns#13]
I suggest adding an entry about diamonds from EIP-2535 Diamond Standard: https://eips.ethereum.org/EIPS/eip-2535

It is an important new Solidity pattern getting adopted by new projects. More info here: https://dev.to/mudgen

**Comment by fravoll** [comment]
Hello @mudgen, thank you for reaching out. This repo is unfortunately not under active development anymore. Hence, I cannot put in the time and passion required to test and add any new patterns to this catalog.
