### ISSUE TITLE
Add security warnings

### ISSUE THREAD

**Issue by maurelian** [fravoll/solidity-patterns#2]
This is a great resource. 👏 

One thing I'd suggest is a brief warning somewhere attached to each pattern to indicate that the code hasn't been audited, and you're making no promises about correctness or safety (unless you have/are). This would be similar to the safe/unsafe patters in our [best practices](https://consensys.github.io/smart-contract-best-practices/)

It's really important in our space to build a culture of security, and this is a small example of how that manifests.

**Comment by fravoll** [comment]
Thanks for your input!
While it is stated in the landing page of the repo/github_pages, it would certainly not hurt to have a notification for each pattern as well.

**Comment by maurelian** [comment]
Thanks for being receptive. 

Feel free to join us in our gitter chat: https://gitter.im/ConsenSys/smart-contract-best-practices, your voice would be welcome.

**Comment by fravoll** [comment]
Disclaimers added as comments to code sections.
