### ISSUE TITLE
Add mention to PREVRANDAO as a possible source of randomness

### ISSUE THREAD

**Issue by Mouradif** [fravoll/solidity-patterns#30]
Since the merge, the Ethereum network has replaced block difficulty with the random number that determined which validator gets to validate a block.

It's used by OpenSea's SeaDrop when trying to shift all token IDs by some random number to ensure a fairer distribution:

https://github.com/ProjectOpenSea/seadrop/blob/main/src/extensions/ERC721PartnerSeaDropRandomOffset.sol#L68

More about it here: https://soliditydeveloper.com/prevrandao

**Comment by fravoll** [comment]
Thanks for the valuable info. Unfortunately I do not intend to maintain this repo as I do not find the time to actively follow the recent developments.
